---
title: "p8105_hw2_yy3421"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

## Problem 1:

Clean up the pols-month csv:
```{r}
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols = 
  read_csv("./data/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -starts_with("prez")) 
```

Clean up the snp.csv
```{r}
snp = 
  read_csv("data/snp.csv") |> 
  separate(date, into = c("month", "day", "year"), convert = TRUE) |> 
  arrange(year, month) |> 
  mutate(month = month.name[month]) |> 
  select(year, month, close)
```

Clean up the unemployment.csv:
```{r}
unemployment = 
  read_csv("data/unemployment.csv") |> 
  rename(year = Year) |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x=_, y = month_df) |> 
  select(year, month, unemployment)
```

Merging the three data frames:

```{r}
data_problem1 = 
  left_join(pols, snp) |> 
  left_join(x = _, y = unemployment)

str(data_problem1)
```

